name: jp_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/startscreen.png
    - assets/T2.png
    - assets/chickcupcake.png
    - assets/bg_mainscreen.png
    - assets/topcard.png
    - assets/Burger_3D.png
    - assets/catcupcake.png
    - assets/icecream.png
